version: '2'

services:
    web-dev:
        image: web-dev:${APP_VERSION}
        build: ./devops/nginx
        ports:
            - ${NGINX_HOST_PORT}:80
            - ${NGINX_HOST_SSL_PORT}:443
        restart: always
        volumes:
            - ./volumes/nginx/logs:/var/log/nginx/
        volumes_from:
            - php-dev:ro
        depends_on:
            - php-dev

    php-base:
        image: php7-base:${APP_VERSION}
        build:
            context: devops/php-fpm/base

    php-dev:
        image: php7-dev:${APP_VERSION}
        build:
            context: devops/php-fpm/dev
            args:
                BASE_IMAGE: php7-base:${APP_VERSION}
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        volumes:
            - ./:/var/www/app/
            - ${HOME}/.gitconfig:/home/www-data/.gitconfig
            - ${HOME}/.git-credentials:/home/www-data/.git-credentials
            - ${HOME}/.ssh:/home/www-data/.ssh
            - composer_cache:/.composer/cache/

    db:
        image: mysql:5.7
        volumes:
            - db:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_HOST_PORT}:3306

volumes:
    db:
    composer_cache: